### ISSUE TITLE
Nutrients are missing

### ISSUE THREAD

**Issue by JarLowrey** [alyssaq/usda-sqlite#4]
`SELECT id,name FROM  nutrient;` should return every nutrient in the database, but the Flavones, Flavanones, Flavonols, Flavan-3-ols, Proanthocyanidin, Anthocyanidins, and potentially more are missing.

**Comment by alyssaq** [comment]
Those nutrients dont appear in the file from USDA: https://www.ars.usda.gov/ARSUserFiles/80400525/Data/SR/SR28/asc/NUTR_DEF.txt

**Comment by alyssaq** [comment]
According to the website, USDA is going to release the next version in FY18. Perhaps it'll be available then.

**Comment by JarLowrey** [comment]
Huh alrighty then. Thanks!
